camunda:
  client:
    mode: saas
    auth:
      clientId: nhOwcn_4Y.KVjgmWYLgmKPt_-Q99xr_Q
      clientSecret: Bn~JPEJfSNXCWp5-QRfpvfX_zx.y78.YC7ezL_GQELnQWkjmVbE.yu~WCRbEjRDW
    region: bru-2
    cluster-id: 7635c41f-f472-4b0b-bee8-8bfd254745fb

api-ninjas:
  key: mZiw9m/sdquYmh4fNlCIPg==fywRllJ4oBX0aARp